robot_position_controller:
  joint_position_controller:
    type: position_controllers/JointPositionController
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7
    pid: {p: 1300.0, i: 0.0, d: 5, i_clamp_min: -130.0, i_clamp_max: 130, antiwindup: True}

  # constraints:
  #     goal_time: 0.5
  #     stopped_velocity_tolerance: 0.2
  # stop_trajectory_duration: 0
  # state_publish_rate:  20
  # action_monitor_rate: 10

